name: Docker Image CI
on:
  push:
    branches:
    - node*
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/hadolint-action@v1.0.2
    #- uses: eshork/gitleaks-action@v1.0.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag evryfs/docker-baseimage:$(date +%s)
